UWB_CALIBRATION_VERSION=EU07

###############################################################################
#SEGMENT CALIBRATION and BOUNDARY are defined.
# cal count = num of segment (MAX 6, 0=disable)
# cal config = [[congfg_1], [config_2]]
# cal boundary = [[boundary_1], [boundary_2]]
# config 1 = for ch9 portrait  [[D(1), PH(1)], [D(2), PH(2)] ... [D(N), PH(N)]]
# config_2 = for ch9 landscape [[D(1), PH(1)], [D(2), PH(2)] ... [D(N), PH(N)]]
# boundary_1 = for ch9 portrait
# boundary_2 = for ch9 landscape

#TILT OFFSET and BOUNDARY are defined.
# offset count = num of tilt (MAX 10)
# offset value = [offset(1), offset(2) ... offset(N)]
# offset boundary

CH5_SEGMENT_CAL_COUNT=0
CH5_SEGMENT_CAL_CONFIG=[]
CH5_SEGMENT_PDOA_BOUNDARY=[]

CH9_SEGMENT_CAL_COUNT=5
CH9_SEGMENT_CAL_CONFIG=[[12, 6], [14, 15], [12, 5], [21, -23], [21, -23],
    [12, -31], [15, -3], [18, 8], [16, 22], [16, 18]]
CH9_SEGMENT_PDOA_BOUNDARY=[[-74, -27, 43, 100],
    [-115, -67, 90, 130]]

TILT_OFFSET_COUNT=2
TILT_OFFSET_VALUE =[0, 7]
TILT_OFFSET_BOUNDARY=[25]

###############################################################################
#TX DELTA PEAK are defined.
# tx delta peak = [[config_1], [config_2]]
# config_1 = for ch5 [LDS ant, patch ant]
# config_2 = for ch9 [LDS ant, patch ant]

TX_DELTA_PEAK=[[0, 4],
    [7, 7]]

###############################################################################
#RX_ANT_FOR_RANGING are defined.
# ch5 ant for ranging = rx config used for better performance in distance service when channel 5
# ch9 ant for ranging = rx config used for better performance in distance service when channel 9

CH5_RX_ANT_FOR_RANGING=[3, 1]

CH9_RX_ANT_FOR_RANGING=[4, 1]

###############################################################################
UWB_CHIP_INFO=SR100T

###############################################################################
# 3D AoA
# Aoa Flipped : 1 (Enable), 0 (Disable)
X_IO=0
Y_IO=0
BETA1=1.61
AOA1_FLIPPED=1
BETA2=-90
AOA2_FLIPPED=1
FoV=50
FP_FILTERING_THRESHOLD=10
FP_FILTERING_MAX_DISTANCE=500